version: '3'

services:
  measure-service:
    depends_on:
      - mongo
    build:
      context: ./service
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      HOST: localhost
      DATABASE_URL: 'mongodb://mongo:27017/measure-repository'
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/service/src
    command: npm start
    stdin_open: true
    tty: true
    # networks:
    #   - blueberry
  
  # measure-app:
  #   depends_on:
  #     - mongo
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   environment:
  #     SERVER_HOST: localhost
  #     SERVER_PORT: 3001
  #     DB_HOST: mongo
  #     DB_PORT: 27017
  #     DB_NAME: draft-repository
  #   ports:
  #     - '3001:3001'
  #   volumes:
  #     - ./src:/usr/src/app/src
  #   command: npm dev -p 3001
  #   stdin_open: true
  #   tty: true

  mongo:
    image: mongo:7.0
    expose:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # networks:
    #   - blueberry

volumes:
  mongo_data:

# networks:
#   blueberry: